# Generated by Django 5.2 on 2025-12-01 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="phone_number",
            field=models.CharField(
                default="",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
