# Generated by Django 5.2 on 2025-12-01 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_useraccount_is_profile_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
