# Generated by Django 5.2 on 2025-12-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
