CREATE TABLE "analytics_productdailymetrics" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "date" date NOT NULL,
    "units_sold" integer NOT NULL,
    "revenue" numeric(10, 2) NOT NULL,
    "profit" numeric(10, 2) NOT NULL,
    "product_id" bigint NOT NULL
);

CREATE TABLE "analytics_refund" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "reason" text NOT NULL,
    "refund_date" timestamp with time zone NOT NULL,
    "refund_amount" numeric(10, 2) NOT NULL,
    "order_item_id" bigint NOT NULL
);

ALTER TABLE "analytics_productdailymetrics" ADD CONSTRAINT "analytics_productdai_product_id_date_6c55c3c6_uniq" UNIQUE ("product_id", "date");
ALTER TABLE "analytics_productdailymetrics" ADD CONSTRAINT "analytics_productdai_product_id_b855a73a_fk_shop_prod" FOREIGN KEY ("product_id") REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "analytics_refund" ADD CONSTRAINT "analytics_refund_order_item_id_a8f4c1d3_fk_orders_or" FOREIGN KEY ("order_item_id") REFERENCES "orders_orderitem" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "analytics_productdailymetrics_product_id_b855a73a" ON "analytics_productdailymetrics" ("product_id");
CREATE UNIQUE INDEX "analytics_refund_order_item_id_key" ON "analytics_refund" ("order_item_id");
