# Generated by Django 5.2 on 2025-12-21 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(db_index=True, max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("initiate", "Initiate"),
                            ("verify", "Verify"),
                            ("callback", "Callback"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(blank=True, null=True)),
                ("result_code", models.CharField(blank=True, max_length=20)),
                ("ref_id", models.CharField(blank=True, max_length=120)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("signature", models.CharField(blank=True, max_length=128)),
                ("message", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "status"],
                        name="payment_pay_event_t_2c2c94_idx",
                    ),
                    models.Index(
                        fields=["order", "created_at"],
                        name="payment_pay_order_i_73c495_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("event_type", "verify"), ("status", "processed")
                        ),
                        fields=("track_id", "event_type", "status"),
                        name="unique_successful_verification",
                    )
                ],
            },
        ),
    ]
