# Generated by Django 5.2 on 2025-12-25 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0002_auto_20240726_1000"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Discount Name"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=10,
                        verbose_name="Discount Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Discount Amount",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Valid From")),
                ("valid_to", models.DateTimeField(verbose_name="Valid To")),
                ("active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Minimum Purchase Amount",
                    ),
                ),
                (
                    "max_usage",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Maximum Overall Usage"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Usage Count"
                    ),
                ),
                (
                    "usage_per_user",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Maximum Usage Per User"
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="DiscountRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        to="shop.category",
                        verbose_name="Applicable Categories",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="discounts.discount",
                        verbose_name="Discount",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        to="shop.product",
                        verbose_name="Applicable Products",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="taggit.tag", verbose_name="Applicable Tags"
                    ),
                ),
                (
                    "variants",
                    models.ManyToManyField(
                        blank=True,
                        to="shop.productvariant",
                        verbose_name="Applicable Variants",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount Rule",
                "verbose_name_plural": "Discount Rules",
            },
        ),
        migrations.CreateModel(
            name="UserDiscountUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_usages",
                        to="discounts.discount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Discount Usage",
                "verbose_name_plural": "User Discount Usages",
                "unique_together": {("user", "discount")},
            },
        ),
    ]
