# Generated by Django 5.2 on 2025-12-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Discount Code",
            ),
        ),
    ]
