# Generated by Django 5.2 on 2025-04-13 10:17
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_picture_url_profile_picture'),
    ]

    operations = [
        TrigramExtension(),
    ]
