# Generated by Django 5.2 on 2025-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_orderitem_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='PE', max_length=10),
        ),
    ]
