# Generated by Django 5.0.3 on 2024-03-25 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_add_coupon_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
