# Generated by Django 5.0.6 on 2024-05-24 10:00

from django.db import migrations, models
import os

def migrate_custom_attachments(apps, schema_editor):
    """
    Migrates data from the old CustomAttachment model to the Media model.
    """
    try:
        CustomAttachment = apps.get_model('blog', 'CustomAttachment')
        Media = apps.get_model('blog', 'Media')

        for attachment in CustomAttachment.objects.all():
            if attachment.file:
                storage_key = attachment.file.name
                file_url = attachment.file.url
                mime_type = 'application/octet-stream'

                if storage_key.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.webp')):
                    mime_type = f'image/{storage_key.split(".")[-1]}'

                media_type = 'image' if 'image' in mime_type else 'file'

                Media.objects.create(
                    storage_key=storage_key,
                    url=file_url,
                    type=media_type,
                    mime=mime_type,
                    size_bytes=attachment.file.size,
                    title=os.path.basename(storage_key),
                    uploaded_by=attachment.uploaded_by,
                    created_at=attachment.created_at
                )
    except LookupError:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0004_postmedia_delete_customattachment'),
    ]

    operations = [
        migrations.RunPython(migrate_custom_attachments, migrations.RunPython.noop),
        migrations.DeleteModel(name='CustomAttachment'),
    ]
