# Generated by Django 5.2.8 on 2025-12-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_migrate_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_hot",
            field=models.BooleanField(default=False),
        ),
    ]
