# Generated by Django 5.0.7 on 2024-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="The stock keeping unit for the product.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
