
# Generated by Django 5.0.6 on 2024-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_fragile',
            field=models.BooleanField(default=False, help_text='Is the product fragile?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_liquid',
            field=models.BooleanField(default=False, help_text='Does the product contain liquid?'),
        ),
    ]
