# Generated by Django 5.2 on 2025-04-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customtag_customtaggeditem_alter_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
