# Generated by Django 5.2 on 2025-11-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_review_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
