# Generated by Django 5.0.6 on 2024-05-20 14:30

from django.db import migrations

def create_default_variants(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    ProductVariant = apps.get_model('shop', 'ProductVariant')
    for product in Product.objects.all():
        ProductVariant.objects.create(
            product=product,
            price=product.price,
            stock=product.stock,
            sku=product.sku
        )

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_merge_20241215_0001'),
    ]

    operations = [
        migrations.RunPython(create_default_variants),
    ]
