import logging

from rest_framework.views import exception_handler

from ecommerce_api.core.api_standard_response import ApiResponse

# Configure a logger for the module
logger = logging.getLogger(__name__)


def custom_exception_handler(exc, context):
    """
    Custom exception handler to standardize API error responses.

    Args:
        exc: The exception instance raised during request processing.
        context: A dictionary containing contextual information about the request.

    Returns:
        Response: A standardized API error response or a generic 500 error response.
    """

    # Call the default DRF exception handler to get the initial response
    response = exception_handler(exc, context)

    if response is not None:
        # Extract the 'detail' attribute from the exception, if available
        detail = getattr(exc, 'detail', None)

        # Check if the detail is a list or dictionary (e.g., validation errors)
        if isinstance(detail, (list, dict)):
            # Use a specific message for validation errors, otherwise a generic one
            message = "Validation failed" if response.status_code == 400 else "Request failed"
            errors = detail  # Include the detailed errors
        else:
            # Handle other types of errors with a generic message
            message = str(detail) if detail else "Request failed"
            errors = None  # No detailed errors available

        # Return a standardized error response with the extracted details
        return ApiResponse.error(
            message=message,
            status_code=response.status_code,
            errors=errors
        )

    # Log the internal server error
    logger.error("Internal server error occurred", exc_info=exc)
    # If no response is generated by the default handler, return a generic 500 error
    return ApiResponse.error(
        message="Internal server error",
        status_code=500
    )
