# Generated by Django 5.2 on 2025-12-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0001_initial"),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorder",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="order",
            name="coupon",
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="discounts.discount",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="discounts.discount",
            ),
        ),
    ]
